### ISSUE TITLE
请问表情怎么在别处显示

### ISSUE THREAD

**Issue by jjxs** [shershen08/emoji-vue#1]
想把他录入数据库,还能提取出来显示

**Comment by shershen08** [comment]
Can you describe a problem in English (or Russian) please ?

**Comment by jjxs** [comment]
How can the expression be displayed elsewhere?

i want to input it into a database, and can extract it.

**Comment by shershen08** [comment]
you should add a `input` event listener to the 
and the process it in the methods block:

```
<VueEmoji @input="onInput"/>

methods: {
  onInput (data) {
    // save `data` to DB
  }
```

**Comment by jjxs** [comment]
How can the picture be displayed?

![image](https://user-images.githubusercontent.com/25605545/44447433-9bea8a80-a61a-11e8-899f-375f1a92a5fc.png)

onInput (data) {
      this.myText = data.data
    }

**Comment by jjxs** [comment]
onInput (data) {
      this.myText = data.data
    }

**Comment by shershen08** [comment]
I can't really reproduce it. Would be easier if you could reproduce the problem demo on https://codepen.io/

This is probably something due to the encoding of the page or the font that is used.

**Comment by shershen08** [comment]
No news on that one @jjxs ?

Closing for now, feel free to reopen if have any updates. I'd start with reproducing in codepen.io or in separate repository - then we can reason and test same thing and share a question with bigger community for help
