### ISSUE TITLE
Maxlength prop feature

### ISSUE THREAD

**Issue by Photoshopper** [shershen08/emoji-vue#3]
Could you add a maxlength prop? I really miss it.

Or maybe do you have any ideas on how to limit max length

**Comment by shershen08** [comment]
I didn't quite understand, what will be the usage of maxlength property. 

Do you mean limit the amount of emojis icons to show ? 
Or the maximum content of the input/textarea field?

**Comment by Photoshopper** [comment]
maximum content of the input/textarea field

**Comment by shershen08** [comment]
@Photoshopper you don't need a special `emoji-vue` feature for this, you can control the number of characters in your input/textarea via your own logic.

See this for example - https://codepen.io/CSWApps/pen/RQbvvp

**Comment by Photoshopper** [comment]
You see,  I need this for emoji-vue, not just for simple input/textarea
