### ISSUE TITLE
Always add emoji at the beginning of the text

### ISSUE THREAD

**Issue by kl3sk** [shershen08/emoji-vue#6]
With you demo under Firefox 63.0 the emoji are inserted at the beginning of the text regardless of the caret position.

**Comment by shershen08** [comment]
Thanks for reporting this one, its same as #4  I guess

**Comment by kl3sk** [comment]
It looks like yes ! But this is not very clear.

**Comment by ruoshui1314** [comment]
chrome has same problem too.

**Comment by cliffordh** [comment]
So does Safari 😢

**Comment by shershen08** [comment]
for problem with adding emoji at the beginning of the text
Please refer to #4 - it's not very readable in title but technically was the first submitted
so all the fixing and updates will be there
