### ISSUE TITLE
Reset text input?

### ISSUE THREAD

**Issue by sheriffmarley** [shershen08/emoji-vue#9]
How can I reset the text in the plugin? 

```js
<VueEmoji @input="onInput" :value="myText" width="500" height="25"/>
...

onInput(event){
                this.messageText = event.data;
            },
```

I tried 
```js
reset(){
  this.myText = "";
  this.messageText = "";
}

```
but it still shows the content.

**Comment by shershen08** [comment]
Indeed that was missing,
I've added it in coming version  - https://github.com/shershen08/emoji-vue/pull/8/commits/5e361eaecb064d06621941d760243acdf1869d74

so it could be executed as follows:

```
clearTextarea(){
      this.$refs.emojiTextarea.clear()
    },  
```

**Comment by shershen08** [comment]
Add this in `0.2.4` and now in readme code sample - https://github.com/shershen08/emoji-vue#use-
